### PR TITLE
`saveAuthenticationRequest` should read `relayState` from `authenticationRequest`

### LINKED ISSUE #18243: CacheSaml2AuthenticationRequestRepository.saveAuthenticationRequest(..) throws IllegalArgumentException
**Describe the bug**
When I try to use CacheSaml2AuthenticationRequestRepository in SAML2 Login , I get the following exception before the redirect, when the <saml2:AuthnRequest> is saved in the CacheSaml2AuthenticationRequestRepository.

```
java.lang.IllegalArgumentException: relayState must not be null
	at org.springframework.util.Assert.notNull(Assert.java:181)
	at org.springframework.security.saml2.provider.service.web.CacheSaml2AuthenticationRequestRepository.saveAuthenticationRequest(CacheSaml2AuthenticationRequestRepository.java:56)
	at org.springframework.security.saml2.provider.service.web.Saml2WebSsoAuthenticationRequestFilter.sendRedirect(Saml2WebSsoAuthenticationRequestFilter.java:113)
	at org.springframework.security.saml2.provider.service.web.Saml2WebSsoAuthenticationRequestFilter.doFilterInternal(Saml2WebSsoAuthenticationRequestFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
```

**Investigation**
In CacheSaml2AuthenticationRequestRepository the relay state is retrieved from a request parameter:

```
	public void saveAuthenticationRequest(AbstractSaml2AuthenticationRequest authenticationRequest,
			HttpServletRequest request, HttpServletResponse response) {
		String relayState = request.getParameter(Saml2ParameterNames.RELAY_STATE);
		Assert.notNull(relayState, "relayState must not be null");
		this.cache.put(relayState, authenticationRequest);
	}
```

In Saml2WebSsoAuthenticationRequestFilter the request parameter is set after saveAuthenticationRequest is called: 

```
	private void sendRedirect(HttpServletRequest request, HttpServletResponse response,
			Saml2RedirectAuthenticationRequest authenticationRequest) throws IOException {
		this.authenticationRequestRepository.saveAuthenticationRequest(authenticationRequest, request, response);
		UriComponentsBuilder uriBuilder = UriComponentsBuilder
			.fromUriString(authenticationRequest.getAuthenticationRequestUri());
		addParameter(Saml2ParameterNames.SAML_REQUEST, authenticationRequest.getSamlRequest(), uriBuilder);
		addParameter(Saml2ParameterNames.RELAY_STATE, authenticationRequest.getRelayState(), uriBuilder);
		addParameter(Saml2ParameterNames.SIG_ALG, authenticationRequest.getSigAlg(), uriBuilder);
		addParameter(Saml2ParameterNames.SIGNATURE, authenticationRequest.getSignature(), uriBuilder);
		response.sendRedirect(redirectUrl);
		String redirectUrl = uriBuilder.build(true).toUriString();
```
	}

**Proposed Solution**

I think the problem can be solved by getting the relayState from the authenticationRequest in CacheSaml2AuthenticationRequestRepository.saveAuthenticationRequest(..):

Replace

`String relayState = request.getParameter(Saml2ParameterNames.RELAY_STATE);`

with

`String relayState = authenticationRequest.getRelayState(); `

### PR DESCRIPTION
**Pull request by therepanic**
I believe there are a number of design implementation mistakes in `CacheSaml2AuthenticationRequestRepository`.

One of them is that in `CacheSaml2AuthenticationRequest#saveAuthenticationRequest`, if `authenticationRequest == null`, we cache the cache itself with a null value, whereas we should be removing it.

Furthermore, I believe we should take the relay state directly from `authenticationRequest` and not from request, since our `Saml2AuthenticationRequestResolver` should resolve and return an object that should be passed to our method.

Closes: gh-18243

### CODE REVIEW

File: saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/CacheSaml2AuthenticationRequestRepository.java [hunk 1]
```diff
@@ -53,7 +54,11 @@ public final class CacheSaml2AuthenticationRequestRepository
 	@Override
 	public void saveAuthenticationRequest(@Nullable AbstractSaml2AuthenticationRequest authenticationRequest,
 			HttpServletRequest request, HttpServletResponse response) {
-		String relayState = request.getParameter(Saml2ParameterNames.RELAY_STATE);
+		if (authenticationRequest == null) {
+			removeAuthenticationRequest(request, response);
+			return;
+		}
```
Comment (therepanic) [inline saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/CacheSaml2AuthenticationRequestRepository.java]: Instead, we cached a null value. See https://github.com/spring-projects/spring-security/blob/main/saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationRequestRepository.java

**Comment by therepanic** [comment]
BTW, the mention of deletion and null was made not so long ago: https://github.com/spring-projects/spring-security/commit/e771ec04b7fbd4ddf73e8fc1c1f1d45670256f0f I believe we reached this conclusion based on the logic of `HttpSessionSaml2AuthenticationRequestRepository`.

File: saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/CacheSaml2AuthenticationRequestRepository.java (hunk 1 above)
Comment (jzheaux) [reply saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/CacheSaml2AuthenticationRequestRepository.java]: good catch!

File: saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/CacheSaml2AuthenticationRequestRepository.java [hunk 2]
```diff
@@ -53,7 +54,7 @@ public AbstractSaml2AuthenticationRequest loadAuthenticationRequest(HttpServletR
 	public void saveAuthenticationRequest(AbstractSaml2AuthenticationRequest authenticationRequest,
 			HttpServletRequest request, HttpServletResponse response) {
 		Assert.notNull(authenticationRequest, "authenticationRequest must not be null");
-		String relayState = request.getParameter(Saml2ParameterNames.RELAY_STATE);
+		String relayState = authenticationRequest.getRelayState();
```
Comment (jzheaux) [inline saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/CacheSaml2AuthenticationRequestRepository.java:57]: good catch! 

Please see 266d2608f1bad9f1a8deae8f2c9ea3b9be866ee2 and ef76ba040d02b4bb34fe1a1cea8cd405426ee67e, which I believe were necessary changes on different branches to address the other concerns you raised in your PR comments. These ultimately simplified this PR to allow focusing on the specific bug.

**Review by jzheaux — APPROVED** [review]

**Comment by jzheaux** [comment]
Thanks, @therepanic! This is now merged into `6.5.x`, `7.0.x`, and `main`

**Comment by patrick-rosendaal** [comment]
Edit: Looks like the fix was overwritten in 3f05f4d30c35e00218eaee4490471145dbf2a451

@jzheaux , are you sure it was merged? I still see (and experience) the bug on the 7.1.x branch:
https://github.com/spring-projects/spring-security/blob/11890f2f49df4e133807b11cfef362ea025bc65c/saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/CacheSaml2AuthenticationRequestRepository.java#L57
